Repository GeodynamicWorldBuilder/WorldBuilder, pull requests merged in 2021-06, with the labels that each got.

#254 Add very basic mpi support
  .github/workflows/test.yml
  CMakeLists.txt
  app/main.cc
  include/world_builder/world.h
  source/world.cc
  tests/CMakeLists.txt
  tests/CPP_MPI/example.cpp
  tests/CPP_MPI/run_CPP_MPI_tests.cmake
  tests/CPP_MPI/run_simple_CPP_MPI_example.log
  tests/CPP_MPI/run_simple_CPP_MPI_test.log
  tests/CPP_MPI/test.cpp
  visualization/main.cc
Labels: add/change code functionality

#259 improve documentation of fault distance declare entries.
  source/features/fault_models/composition/uniform.cc
  source/features/fault_models/temperature/uniform.cc
Labels: documentation enhancement

#260 Change fault linear entries
  CHANGELOG.md
  source/features/fault_models/temperature/linear.cc
  tests/data/fault_constant_angles_cartesian_2.wb
  tests/visualization/fault.wb
Labels: add/change user functionality

#273 Fix linear temperatures
  CHANGELOG.md
  source/features/continental_plate_models/temperature/linear.cc
  source/features/fault_models/temperature/linear.cc
  source/features/subducting_plate_models/temperature/linear.cc
  tests/data/continental_plate.wb
  tests/data/fault_constant_angles_cartesian.wb
  tests/data/mantle_layer_cartesian.wb
  tests/data/oceanic_plate_cartesian.wb
  tests/data/subducting_plate_constant_angles_cartesian.wb
  tests/unit_tests/unit_test_world_builder.cc
Labels: bug

#282 Adding the option to compress vtu files
  CHANGELOG.md
  CMakeLists.txt
  include/vtu11/LICENSE
  include/vtu11/vtu11.hpp
  tests/visualization/fault.grid
  tests/visualization/fault.vtu
  tests/visualization/subducting_plate_manual3.grid
  tests/visualization/subducting_plate_manual3.vtu
  visualization/main.cc
Labels: add/change user functionality

#289 Avoid map containers for parameter transfer
  CHANGELOG.md
  include/world_builder/features/fault_models/composition/interface.h
  include/world_builder/features/fault_models/composition/uniform.h
  include/world_builder/features/fault_models/grains/interface.h
  include/world_builder/features/fault_models/grains/random_uniform_distribution.h
  include/world_builder/features/fault_models/grains/uniform.h
  include/world_builder/features/fault_models/temperature/adiabatic.h
  include/world_builder/features/fault_models/temperature/interface.h
  include/world_builder/features/fault_models/temperature/linear.h
  include/world_builder/features/fault_models/temperature/uniform.h
  include/world_builder/features/subducting_plate_models/composition/interface.h
  include/world_builder/features/subducting_plate_models/composition/uniform.h
  include/world_builder/features/subducting_plate_models/grains/interface.h
  include/world_builder/features/subducting_plate_models/grains/random_uniform_distribution.h
  include/world_builder/features/subducting_plate_models/grains/uniform.h
  include/world_builder/features/subducting_plate_models/temperature/adiabatic.h
  include/world_builder/features/subducting_plate_models/temperature/interface.h
  include/world_builder/features/subducting_plate_models/temperature/linear.h
  include/world_builder/features/subducting_plate_models/temperature/plate_model.h
  include/world_builder/features/subducting_plate_models/temperature/uniform.h
  include/world_builder/utilities.h
  source/features/fault.cc
  source/features/fault_models/composition/uniform.cc
  source/features/fault_models/grains/random_uniform_distribution.cc
  source/features/fault_models/grains/uniform.cc
  source/features/fault_models/grains/uniform.cc_backup
  source/features/fault_models/temperature/adiabatic.cc
  source/features/fault_models/temperature/linear.cc
  source/features/fault_models/temperature/uniform.cc
  source/features/subducting_plate.cc
  source/features/subducting_plate_models/composition/uniform.cc
  source/features/subducting_plate_models/grains/random_uniform_distribution.cc
  source/features/subducting_plate_models/grains/uniform.cc
  source/features/subducting_plate_models/temperature/adiabatic.cc
  source/features/subducting_plate_models/temperature/linear.cc
  source/features/subducting_plate_models/temperature/plate_model.cc
  source/features/subducting_plate_models/temperature/uniform.cc
  source/utilities.cc
  tests/unit_tests/unit_test_world_builder.cc
Labels: performance
